services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mahitday
    pull_policy: build
    volumes:
      - /storage/mahitday/uploads/:/app/uploads/:rw,z
    restart: always
    env_file:
      - stack.env
    labels:
      # Traefik configuration discovery
      # https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.mahitday-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.mahitday-redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.mahitday-http.middlewares=mahitday-redirect'
      - 'traefik.http.routers.mahitday-http.rule=Host(`mahitday.docchula.com`)'
      - 'traefik.http.routers.mahitday-http.entrypoints=web'
      - 'traefik.http.routers.mahitday-https.rule=Host(`mahitday.docchula.com`)'
      - 'traefik.http.routers.mahitday-https.entrypoints=websecure'
      - 'traefik.http.routers.mahitday-https.tls.certresolver=leresolver'
      - 'traefik.http.services.mahitday-https.loadbalancer.server.port=3000'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
